### PR TITLE
Replace dropbear-sshd with crypt-ssh in README.md

### PR DESCRIPTION
**Pull request by Lilleengen**

### CODE REVIEW

**Comment by rbu** [comment]
This line is not even necessary anymore, at least in RHEL7 and Fedora 23. I haven't tried 22. Can you confirm that the module starts without the "dracutmodule" line altogether?

I've been meaning to merge Artem's README (in the modules directory) with the old README as well, the steps to install definitely need work.

**Comment by rbu** [comment]
Oh, I forgot to mention: Thank you for the pull request!

**Comment by Lilleengen** [comment]
Don't really think i have tried without the line. Will report back within 24 hours.

**Comment by rbu** [comment]
@Lilleengen, I've just pushed a large README update which removes the paragraph you changed. I don't think it is necessary with recent dracut versions.

Thanks again.

**Pull request closed without merging**
