### PR TITLE
Specify PEM format for ssh-keygen, to ensure private key can be read by dropbearconvert

### PR DESCRIPTION
**Pull request by sea36**
Fixes issue #32

### CODE REVIEW

**Comment by champtar** [comment]
I confirm this fix Fedora28 / openssh 7.8
Can someone merge this ?

**Review by artem-sidorenko — APPROVED** [review]

**Comment by artem-sidorenko** [comment]
@sea36 @champtar thank you!

**Comment by champtar** [comment]
@artem-sidorenko are you planning a 1.0.8 release ?

**Comment by champtar** [comment]
(so https://copr.fedorainfracloud.org/coprs/rbu/dracut-crypt-ssh/ can be updated)

**Comment by utoddl** [comment]
Is anybody going to pull the trigger on this? 1.0.7-1 with this problem present is still current as of 2020-03-16.

**Comment by XertroV** [comment]
yeah - just ran into this too. looks like this has been sitting around for like 18 months...

**Comment by nebril** [comment]
Would be nice to get a release, but it's not a very big deal since building from source is an option.

**Comment by davidhrinaldo** [comment]
I'm also having the same problem. Any chance for a release soon?

**Pull request merged**
