### PR TITLE
Add note about EFI grub

### PR DESCRIPTION
**Pull request by ghost**
I spent more than a couple of hours on this issue, let's hope this might save others the trouble :)

### CODE REVIEW

**Comment by stikonas** [comment]
I guess change looks fine for Fedora. On the other hand, grub.cfg is not even located in /etc/ on most distros... I wonder if this can be written in a more distro agnostic way.

**Comment by vbraun** [comment]
I don't think there is a distro-agnostic way. At least mentioning that there might be another location would surely be helpful to other distro users.

The grub configuration file isn't in /etc/ on Fedora either, /etc/{grub2,grub2-efi}.cfg are symlinks to the actual location.

**Comment by artem-sidorenko** [comment]
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/43

**Comment by ahesford** [comment]
WONTFIX, especially because this section has been rewritten to de-emphasize GRUB.

**Pull request closed without merging**
